fix offer access type validator
cyfronet-fid/whitelabel-marketplace pull request #67
Opened 2024-08-07 15:20 UTC by maria-j-k

https://github.com/cyfronet-fid/marketplace/issues/3263

2024-08-08 08:58 UTC, Marcelinna approved these changes

2024-08-08 11:11 UTC, goreck888 requested changes

2024-08-08 11:11 UTC, goreck888 commented on app/models/offer.rb
>        errors.add(:order_type, "must be the same as in the service: #{service.order_type}")
You have code duplication and muliple nested if statements. What do you think about writing something like this?
```
  def same_order_type_as_in_service
    other_services = service.offers.published.reject { |o| o&.id == id }
    other_check = other_services.none? { |o| o.order_type == service&.order_type }
    if (other_services.empty? || other_check ) && order_type != service.order_type
      errors.add(:order_type, "must be the same as in the service: #{service.order_type}")
    end
  end
```

2024-08-09 10:49 UTC, goreck888 approved these changes

2024-08-09 10:55 UTC, merged